name: Build CLI Native Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, macos]
        include:
          - os: linux
            jre_url: https://github.com/adoptium/temurin21-binaries/releases/latest/download/OpenJDK21U-jre_x64_linux_hotspot.tar.gz
            archive_ext: tar.gz
          - os: windows
            jre_url: https://github.com/adoptium/temurin21-binaries/releases/latest/download/OpenJDK21U-jre_x64_windows_hotspot.zip
            archive_ext: zip
          - os: macos
            jre_url: https://github.com/adoptium/temurin21-binaries/releases/latest/download/OpenJDK21U-jre_x64_mac_hotspot.tar.gz
            archive_ext: tar.gz

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Download JRE
        run: |
          curl -L -o jre.${{ matrix.archive_ext }} "${{ matrix.jre_url }}"
          if [[ "${{ matrix.archive_ext }}" == "tar.gz" ]]; then
            mkdir jre && tar -xzf jre.tar.gz -C jre --strip-components=1
          else
            unzip jre.zip -d jre && mv jre/* jre-runtime && rm -rf jre && mv jre-runtime jre
          fi

      - name: Package with jpackage
        run: |
          mkdir output
          jpackage \
            --name edp-cli \
            --type app-image \
            --input target \
            --main-jar edp-cli-1.0.jar \
            --main-class EdpCli \
            --runtime-image jre \
            --dest output
          
          cd output
          zip -r ../edp-cli-${{ matrix.os }}.zip edp-cli
          cd ..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edp-cli-${{ matrix.os }}
          path: edp-cli-${{ matrix.os }}.zip
