name: Build EDP CLI for All Platforms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build shaded JAR
        run: mvn clean package -DskipTests

      - name: Create dist directory
        run: mkdir dist

      # ---- Build for Linux ----
      - name: Download Linux JRE
        run: |
          curl -L -o linux-jre.tar.gz https://github.com/adoptium/temurin21-binaries/releases/latest/download/OpenJDK21U-jre_x64_linux_hotspot.tar.gz
          mkdir -p jre/linux
          tar -xzf linux-jre.tar.gz -C jre/linux --strip-components=1

      - name: Package Linux image
        run: |
          jpackage \
            --type app-image \
            --input target \
            --main-jar edp-cli-1.0.jar \
            --main-class EdpCli \
            --name edp-cli \
            --runtime-image jre/linux \
            --dest dist/linux

      # ---- Build for Windows ----
      - name: Download Windows JRE
        run: |
          curl -L -o windows-jre.zip https://github.com/adoptium/temurin21-binaries/releases/latest/download/OpenJDK21U-jre_x64_windows_hotspot.zip
          mkdir -p jre/windows
          unzip -q windows-jre.zip -d jre/windows
          mv jre/windows/*/* jre/windows/ || true

      - name: Package Windows image
        run: |
          jpackage \
            --type app-image \
            --input target \
            --main-jar edp-cli-1.0.jar \
            --main-class EdpCli \
            --name edp-cli \
            --runtime-image jre/windows \
            --dest dist/windows

      # ---- Build for macOS ----
      - name: Download macOS JRE
        run: |
          curl -L -o mac-jre.tar.gz https://github.com/adoptium/temurin21-binaries/releases/latest/download/OpenJDK21U-jre_x64_mac_hotspot.tar.gz
          mkdir -p jre/macos
          tar -xzf mac-jre.tar.gz -C jre/macos --strip-components=1

      - name: Package macOS image
        run: |
          jpackage \
            --type app-image \
            --input target \
            --main-jar edp-cli-1.0.jar \
            --main-class EdpCli \
            --name edp-cli \
            --runtime-image jre/macos \
            --dest dist/macos

      # ---- Zip outputs ----
      - name: Zip all builds
        run: |
          cd dist
          zip -r edp-cli-linux.zip linux
          zip -r edp-cli-windows.zip windows
          zip -r edp-cli-macos.zip macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edp-cli-binaries
          path: dist/*.zip
