name: Build and Package CLI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      MAIN_CLASS: EdpCli
      JAR_NAME: edp-cli-1.0.jar         # ✅ Fixed: actual jar name from Maven
      APP_NAME: edp-cli

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build shaded JAR with Maven
        run: mvn clean package -DskipTests

        # Optional: dynamically detect final jar version from Maven (if needed)
        # - name: Set jar name dynamically
        #   run: |
        #     echo "JAR_NAME=$(ls target/edp-cli-*.jar | grep -v 'original' | xargs -n 1 basename)" >> $GITHUB_ENV

      - name: Create output directory
        run: mkdir -p dist

      - name: Package with jpackage (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          jpackage `
            --input target `
            --name $env:APP_NAME `
            --main-jar $env:JAR_NAME `
            --main-class $env:MAIN_CLASS `
            --type exe `
            --dest dist `
            --win-console `
            --java-options "-Xmx512m"

      - name: Package with jpackage (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          jpackage \
            --input target \
            --name $APP_NAME \
            --main-jar $JAR_NAME \
            --main-class $MAIN_CLASS \
            --type app-image \
            --dest dist \
            --java-options "-Xmx512m"

      - name: Package with jpackage (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          jpackage \
            --input target \
            --name $APP_NAME \
            --main-jar $JAR_NAME \
            --main-class $MAIN_CLASS \
            --type app-image \
            --dest dist \
            --java-options "-Xmx512m"

      - name: Upload packaged binary
        uses: actions/upload-artifact@v4
        with:
          name: edp-cli-${{ matrix.os }}
          path: dist/
