name: Build and Package CLI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      MAIN_CLASS: EdpCli
      JAR_NAME: edp-cli.jar
      APP_NAME: edp-cli

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build shaded JAR with Maven
        run: mvn clean package -DskipTests

      - name: Create output directory
        run: mkdir -p dist

      - name: Package with jpackage (Windows)
        if: runner.os == 'Windows'
        run: |
          jpackage `
            --input target `
            --name $Env:APP_NAME `
            --main-jar $Env:JAR_NAME `
            --main-class $Env:MAIN_CLASS `
            --type exe `
            --dest dist `
            --win-console `
            --java-options "-Xmx512m"

      - name: Package with jpackage (Linux)
        if: runner.os == 'Linux'
        run: |
          jpackage \
            --input target \
            --name $APP_NAME \
            --main-jar $JAR_NAME \
            --main-class $MAIN_CLASS \
            --type deb \
            --dest dist \
            --java-options "-Xmx512m"

      - name: Package with jpackage (macOS)
        if: runner.os == 'macOS'
        run: |
          jpackage \
            --input target \
            --name $APP_NAME \
            --main-jar $JAR_NAME \
            --main-class $MAIN_CLASS \
            --type pkg \
            --dest dist \
            --java-options "-Xmx512m"

      - name: Upload packaged binary
        uses: actions/upload-artifact@v4
        with:
          name: edp-cli-${{ matrix.os }}
          path: dist/
