name: Build Cross-Platform CLI with JRE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build shaded JAR
        run: mvn clean package -DskipTests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edp-cli-bundles
          path: dist/*

      - name: Commit and Push ZIPs to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Move ZIPs to a permanent folder in repo (e.g., releases)
          mkdir -p releases
          cp dist/* releases/

          git add releases/*
          git commit -m "Add CLI bundles for commit $GITHUB_SHA" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
