name: Build CLI Distributables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: edp-cli
      VERSION: 1.0
      MAIN_CLASS: EdpCli
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Package for All OS
        run: |
          rm -rf dist
          mkdir dist

          # Create custom JRE
          jlink --output custom-jre --add-modules java.base,java.logging,java.sql

          # Linux
          jpackage --type app-image \
                   --name $APP_NAME \
                   --input target \
                   --main-jar edp-cli-1.0.jar \
                   --main-class $MAIN_CLASS \
                   --java-options "--enable-preview" \
                   --dest dist/linux \
                   --runtime-image custom-jre

          # Windows (folder output)
          jpackage --type app-image \
                   --name $APP_NAME \
                   --input target \
                   --main-jar edp-cli-1.0.jar \
                   --main-class $MAIN_CLASS \
                   --java-options "--enable-preview" \
                   --dest dist/windows \
                   --runtime-image custom-jre \
                   --target-platform windows

          # macOS (folder output)
          jpackage --type app-image \
                   --name $APP_NAME \
                   --input target \
                   --main-jar edp-cli-1.0.jar \
                   --main-class $MAIN_CLASS \
                   --java-options "--enable-preview" \
                   --dest dist/macos \
                   --runtime-image custom-jre \
                   --target-platform mac

          cd dist && zip -r ${APP_NAME}-linux.zip linux/${APP_NAME}
          cd dist && zip -r ${APP_NAME}-windows.zip windows/${APP_NAME}
          cd dist && zip -r ${APP_NAME}-macos.zip macos/${APP_NAME}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-builds
          path: dist/*.zip
