name: Build and Package EDP CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build shaded JAR
        run: mvn clean package -DskipTests

      - name: Test CLI JAR
        run: |
          echo "Testing CLI..."
          java -jar target/edp-cli-1.0.jar say-bye --name Aarsh

      # Linux bundle
      - name: Create Linux bundle
        run: |
          mkdir -p dist/linux/lib dist/linux/bin dist/linux/runtime
          cp target/edp-cli-1.0.jar dist/linux/lib/
          wget -q https://download.bell-sw.com/java/17.0.12+7/bellsoft-jre17.0.12+7-linux-amd64-full.tar.gz
          tar -xzf bellsoft-jre17.0.12+7-linux-amd64-full.tar.gz -C dist/linux/runtime --strip-components=1
          echo '#!/bin/bash' > dist/linux/bin/edp-cli
          echo 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"' >> dist/linux/bin/edp-cli
          echo '"$DIR/../runtime/bin/java" -jar "$DIR/../lib/edp-cli-1.0.jar" "$@"' >> dist/linux/bin/edp-cli
          chmod +x dist/linux/bin/edp-cli

      # Windows bundle
      - name: Create Windows bundle
        run: |
          mkdir -p dist/windows/lib dist/windows/bin dist/windows/runtime
          cp target/edp-cli-1.0.jar dist/windows/lib/
          wget -q https://download.bell-sw.com/java/17.0.12+7/bellsoft-jre17.0.12+7-windows-amd64-full.zip
          unzip -q bellsoft-jre17.0.12+7-windows-amd64-full.zip -d dist/windows/runtime
          mv dist/windows/runtime/*/* dist/windows/runtime/
          echo '@echo off' > dist/windows/bin/edp-cli.bat
          echo 'set DIR=%~dp0' >> dist/windows/bin/edp-cli.bat
          echo '"%DIR%..\runtime\bin\java.exe" -jar "%DIR%..\lib\edp-cli-1.0.jar" %*' >> dist/windows/bin/edp-cli.bat

      - name: Zip bundles
        run: |
          cd dist
          zip -r ../edp-cli-linux.zip linux
          zip -r ../edp-cli-windows.zip windows
          cd ..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edp-cli-bundles
          path: |
            edp-cli-linux.zip
            edp-cli-windows.zip
